### ISSUE TITLE
Perfolizer 0.3.0 to Nuget

### ISSUE THREAD

**Issue by zetomatoz** [AndreyAkinshin/perfolizer#3]
Hello,

@AndreyAkinshin, is there an upcoming plan to publish Perfolizer v.0.3.0 to [Nuget](https://www.nuget.org/packages/Perfolizer/)?

Cheers

**Comment by AndreyAkinshin** [comment]
Hello @zetomatoz.

Sorry for the late reply. Currently, I have no specific plans, but I hope to release it in the next few months. There is a lot of work which is related to fixing minor bugs, improving APIs, writing minimal documentation, etc.

Meanwhile, you can use the nightly version of Perfolizer from myget. Here is an example of NuGet.Config:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="perfolizer-nightly" value="https://www.myget.org/F/perfolizer/api/v3/index.json" />
  </packageSources>
</configuration>
```

**Comment by AndreyAkinshin** [comment]
@zetomatoz Perfolizer 3.x is available on NuGet: https://www.nuget.org/packages/Perfolizer/0.3.5
